/**
 * Slamby API
 * Slamby API
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

/**
 * File Parser result object
 */
export interface IFileParserResult {
    

    /**
     * The text content of sent document. Can be empty.
     */
    Content?: string;

    /**
     * The title of the document. Can be null or empty.
     */
    Title?: string;

    Date?: string;

    /**
     * The author of the document. Can be null or empty.
     */
    Author?: string;

    /**
     * Keywords of the document. Can be null or empty.
     */
    Keywords?: string;

    /**
     * The type of the document (e.g.: application/pdf). Can be empty.
     */
    ContentType?: string;

    /**
     * The length of the received document.
     */
    ContentLength?: number;

    /**
     * Detected language of the document (e.g.: en). Can be empty.
     */
    Language?: string;
}

