/**
 * Slamby API
 * Slamby API
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface IFilter {
    

    /**
     * You can direct your search queries into specific tags.   By giving the required tag id list, the filter will affect just the provided tags.   It's useful to create powerful search queries inside given tags.   To filter inside a whole dataset, you can set this field to empty
     */
    TagIdList?: Array<string>;

    /**
     * Set here the filters. The value is the query string you want to apply.   Can be BOOL expressions. You can use these: AND, OR, NOT.   For example: 'searchforthis AND NOT butnotthis'.   Also you can use wildcards. For example: 'exampl*'.   If you want to search in a specified field, than do this: 'title:searchthisinthetitle'
     */
    Query?: string;
}

