/**
 * Slamby API
 * Slamby API
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

/**
 * Contains calculated values for the tag
 */
export interface ITagProperties {
    

    /**
     * A tag list contains parent path elements
     */
    Paths?: Array<models.IPathItem>;

    /**
     * The level of the tag in the hierarchy (root level is: 0)
     */
    Level?: number;

    /**
     * If the tag is a leaf tag. Leaf tag means the tag is not a parent of any other tags
     */
    IsLeaf?: boolean;

    /**
     * Document count for the tag
     */
    DocumentCount?: number;

    /**
     * Word count for the tag
     */
    WordCount?: number;
}

